USE codeup_test_db;

TRUNCATE albums;
INSERT INTO albums (artist, name, release_date, sales, genre)
VALUES('Michael Jackson',                  'Thriller',                                '1982',    47300000,     'Pop, Rock, R&B'),
	  ('AC/DC',                            'Back in Black',                           '1980',    26100000,     'Hard rock'),
	  ('Pink Floyd' ,                      'The Dark Side of the Moon' ,              '1973',    24200000,     'Progressive rock'),
	  ('Whitney Houston / Various artists','The Bodyguard',                           '1992',    27400000,     'R&B, Soul, Pop, Soundtrack'),
	  ('Meat Loaf',                        'Bat Out of Hell',                         '1977',    21500000,     'Hard rock, Progressive rock'),
	  ('Eagles',                           'Their Greatest Hits',                     '1976',    32200000,     'Rock, Soft rock, Folk rock'),
	  ('Bee Gees / Various artists',       'Saturday Night Fever',                    '1977',    20600000,     'Disco'),
	  ('Fleetwood Mac',                    'Rumours',                                 '1977',    27900000,     'Soft rock'),
	  ('Shania Twain',                     'Come On Over',                            '1997',    29600000,     'Country, Pop'),
	  ('Led Zeppelin',                     'Led Zeppelin IV',                         '1971',    29000000,     'Hard rock, Heavy metal, Folk'),
	  ('Adele',                            '21',                                      '2011',    25300000,     'Pop, Soul'),
	  ('Michael Jackson',                  'Bad',                                     '1987',    23600000,     'Pop, Funk, Rock'),
	  ('Alanis Morissette',                'Jagged Little Pill',                      '1995',    24400000,     'Alternative rock'),
	  ('Celine Dion',                      'Falling into You',                        '1996',    20200000,     'Pop, Soft rock'),
	  ('The Beatles',                      'Sgt. Pepper\'s Lonely Hearts Club Band',  '1967',    13100000,     'Rock'),
	  ('Eagles',                           'Hotel California',                        '1976',    21500000,     'Rock, Soft rock, Folk rock'),
	  ('Michael Jackson',                  'Dangerous',                               '1991',    19400000,     'Rock, Funk, Pop'),
	  ('Various artists',                  'Dirty Dancing',	                          '1987',    17900000,     'Pop, Rock, R&B'),
	  ('Celine Dion',                      'Let\'s Talk About Love',                  '1997',    19300000,     'Pop, Soft rock'),
	  ('The Beatles',                      '1',                                       '2000',    22600000,     'Rock'),
	  ('Madonna',                          'The Immaculate Collection',               '1990',    19400000,     'Pop, Dance'),
	  ('The Beatles',                      'Abbey Road',                              '1969',    14400000,     'Rock'),
	  ('Bruce Springsteen',                'Born in the U.S.A.',                      '1984',    19600000,     'Rock'),
	  ('Dire Straits',                     'Brothers in Arms',                        '1985',    17700000,     'Rock, Pop'),
	  ('James Horner',                     'Titanic: Music from the Motion Picture',  '1997',    18100000,     'Soundtrack'),
	  ('Metallica',                        'Metallica',                               '1991',    21200000,     'Thrash metal, Heavy metal'),
	  ('Nirvana',                          'Nevermind',                               '1991',    16700000,     'Grunge, Alternative rock'),
	  ('Pink Floyd',                       'The Wall',                                '1979',    17600000,     'Progressive rock'),
	  ('Santana',                          'Supernatural',                            '1999',    20500000,     'Rock'),
	  ('Guns N\' Roses',                   'Appetite for Destruction',                '1987',    21600000,     'Heavy metal, Hard rock'),
	  ('Linkin Park',                      'Hybrid Theory',                           '2000',    15000000,     'Nu metal, Rap metal, Alternative metal')     